# Generated by Django 5.1.2 on 2025-01-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_quiz_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choice_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
